version: '3'
services:
  bevfusion_val:
    volumes:
      - ${NUSCENE_ROOT}/maps:/bevfusion/data/nuscenes/maps
      - ${NUSCENE_ROOT}/nuscenes_gt_database:/bevfusion/data/nuscenes/nuscenes_gt_database
      - ${NUSCENE_ROOT}/v1.0-trainval:/bevfusion/data/nuscenes/v1.0-trainval
      - ${NUSCENE_ROOT}/nuscenes_dbinfos_train.pkl:/bevfusion/data/nuscenes/nuscenes_dbinfos_train.pkl
      - ${NUSCENE_ROOT}/nuscenes_infos_val.pkl:/bevfusion/data/nuscenes/nuscenes_infos_val.pkl

      - ${NUSCENE_ROOT}/samples/RADAR_BACK_LEFT:/bevfusion/data/nuscenes/samples/RADAR_BACK_LEFT
      - ${NUSCENE_ROOT}/samples/RADAR_BACK_RIGHT:/bevfusion/data/nuscenes/samples/RADAR_BACK_RIGHT
      - ${NUSCENE_ROOT}/samples/RADAR_FRONT:/bevfusion/data/nuscenes/samples/RADAR_FRONT
      - ${NUSCENE_ROOT}/samples/RADAR_FRONT_LEFT:/bevfusion/data/nuscenes/samples/RADAR_FRONT_LEFT
      - ${NUSCENE_ROOT}/samples/RADAR_FRONT_RIGHT:/bevfusion/data/nuscenes/samples/RADAR_FRONT_RIGHT

      - ${NUSCENE_ROOT}/sweeps:/bevfusion/data/nuscenes/sweeps

      - ${NUSCENE_L_ROOT}:/bevfusion/data/nuScenes-CL
      - ${NUSCENE_C_ROOT}:/bevfusion/data/nuScenes-CC